node {
  stage('do something with git') {  
    sshagent (credentials: ['git']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs rajeshbala01@github.com/rajeshbala01/jenkin-course.git master |awk "{print $1}"'
    }
  }
}
